# Занятие 2. Библиотеки и инструменты для анализа данных. Математика в машинном обучении
## Часть 1. Работа с векторами в библиотеке NumPy

**Numpy** - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.

In [ ]:
# Python 2 and 3 compatibility
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
# отключим предупреждения Anaconda
import warnings
warnings.simplefilter('ignore')
import numpy as np

In [ ]:
?np.array

In [ ]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [ ]:
!python --version

Python 3.10.12


Такой массив может содержать:
- значения физических величин в разые моменты времени при моделировании
- значения сигнала, измеренного прибором
- интенсивности пикселов
- 3D координаты объектов, полученных, например, при МРТ
- ...


**Зачем NumPy:** Эффективность базовых операций


In [ ]:
L = range(1000)

In [ ]:
%timeit [i**2 for i in L]

302 µs ± 4.45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
a = np.arange(1000)

In [ ]:
%timeit a**2

942 ns ± 181 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Интерактивная справка


In [ ]:
a.max

<function ndarray.max>

поиск в документации


In [ ]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.char.array
    Create a `chararray`.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.from_dlpack
    Create a NumPy array from an object implementing the ``__dlpack__``
numpy.rec.fromarrays
    Create a record array from a (flat) list of arrays
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    diagflat
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.rec.fromfile
    Create an array from binary file data
numpy.rec.fromstring
    Create a record array from binary data
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.rec.fromrecords
    Create a recarray from a lis

In [ ]:
!pwd

/content


In [ ]:
np.con*?

#### Библиотеку принято импортировать так

In [ ]:
import numpy as np

## Создание массивов

* **1-D**:


In [ ]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
len(a)

4

* **2-D, 3-D, ...**:


In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
len(b)     # returns the size of the first dimension

2

In [ ]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [ ]:
c.shape

(2, 2, 1)

## Методы для создания массивов

На практике мы редко добавляем элементы по одному


- Равномерно распределенные элементы:


In [ ]:
a = np.arange(10) # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

- по числу элементов:


In [ ]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

- Часто встречающиеся массивы:


In [ ]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [ ]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

* `np.random` генерация случайных чисел (Mersenne Twister PRNG):

In [ ]:
np.random.seed(1234)
a = np.random.rand(4)       # uniform in [0, 1]
a

array([0.19151945, 0.62210877, 0.43772774, 0.78535858])

In [ ]:
b = np.random.randn(4)      # Gaussian
b

array([-0.72058873,  0.88716294,  0.85958841, -0.6365235 ])

In [ ]:
np.random.seed(1234)        # Setting the random seed

## Основные типы данных NumPy

Точка после числа означает, что это тип данных `float64`


In [ ]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [ ]:
b = np.array([1.1, 2.2, 3.5])
b.dtype

dtype('float64')

Можно задать тип данных явно. По умолчанию - `float64`

In [ ]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

In [ ]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

Прочие типы данных:

- Комплексные числа


In [ ]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

 - Bool


In [ ]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

- Строки

На строки память выделяется "жадно" - по максимальному числу литер в строке.
В этом примере на каждую строку выделяется по 7 литер, и тип данных - 'S7'

In [ ]:
f = np.array(['Bonjour', 'Hello', 'Hallo',])
f.dtype     # <--- strings containing max. 7 letters

dtype('<U7')

## Основы визуализации

$ ipython notebook --pylab=inline

Или из тетрадки:

In [ ]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Параметр `inline` говорит серверу IPython о том, что результаты будут отображаться в самой тетрадке, а не в новом окне.


Импортируем *Matplotlib*


In [ ]:
import matplotlib.pyplot as plt  # the tidy way

In [ ]:
x = np.linspace(0, 3, 20)
y = np.linspace(0, 9, 20)
plt.plot(x, y)       # line plot
plt.show()           # <-- shows the plot (not needed with pylab)

Или с использованием *pylab*:


In [ ]:
plot(x, y)       # line plot

Использование `import matplotlib.pyplot as plt` рекомендуется для скриптов, а `pylab` - в тетрадках IPython.

 - Отображение одномерных массивов:


In [ ]:
x = np.linspace(0, 3, 20)
y = np.linspace(0, 9, 20)
plt.plot(x, y)       # line plot

In [ ]:
plt.plot(x, y, 'x')  # dot plot

- Отображение двухмерных массивов (например, изображений):


In [ ]:
image = np.random.rand(30, 30)
plt.imshow(image, cmap=plt.cm.hot)
plt.colorbar()

## Индексирование массивов и срезы

В целом так же, как со встроенными последовательностями Python (например, как со списками).


In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0], a[2], a[-1]

(0, 2, 9)

Работает и популярный в Python способ отражения массива:


In [ ]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Для многомерных массивов индексы - это кортежи целых чисел


In [ ]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [ ]:
a[1, 1]

1

In [ ]:
a[2, 1] = 10 # third line, second column
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [ ]:
a[1,::]

array([0, 1, 0])

**Срезы**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:9:3] # [start:end:step]

array([2, 5, 8])

Последний индекс не включается

In [ ]:
a[0:4]

array([0, 1, 2, 3])

По умолчанию \`start\` -  0,
\`end\` - индекс последнего элемента, \`step\` - 1:


In [ ]:
a[1:3]

array([1, 2])

In [ ]:
a[::2]

array([0, 2, 4, 6, 8])

In [ ]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

Можно совмещать присваивание и срез:


In [ ]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [ ]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## Пример. Матрица делителей

Отобразить матрицу, в которой вычеркивается **(x, y)**, если **y** делится на **x**.

In [ ]:
from IPython.display import Image
Image(filename='../../img/prime-sieve.png')

* Создадим массив `is_prime`, заполненний значениями True


In [ ]:
is_prime = np.ones((100,), dtype=bool)

* Вычеркнем 0 и 1 как не являющиеся простыми:


In [ ]:
is_prime[:2] = 0

* Для каждого наутрального `j` начиная с  2, "вычеркнем" числа, ему кратные:


In [ ]:
N_max = int(np.sqrt(len(is_prime)))
for j in range(2, N_max):
    is_prime[2*j::j] = False

is_prime

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False, False], dtype=bool)

## Индексирование масками

In [ ]:
np.random.seed(3)
a = np.random.random_integers(0, 20, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [ ]:
(a % 3 == 0)

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False], dtype=bool)

In [ ]:
a[(a % 3 == 0)] # or,  a[a%3==0]

array([ 3,  0,  9,  6,  0, 12])

Индесирование маской может быть очень полезным для присваивания значений части элементов массива:


In [ ]:
a[a % 3 == 0] = -1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

### Индексирование массивом целых чисел

In [ ]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a[[2, 3, 2, 4, 2]]  # note: [2, 3, 2, 4, 2] is a Python list

array([20, 30, 20, 40, 20])

In [ ]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

In [ ]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
idx.shape

(2, 2)

In [ ]:
a[idx]

array([[3, 4],
       [9, 7]])